PROGRAM=cv-mandelbrot
CFLAGS= -std=c++17 `pkg-config opencv4 --cflags` 
LDFLAGS= `pkg-config opencv4 --libs`


all: $(PROGRAM)

$(PROGRAM): main.cpp
	$(CXX) -o $(PROGRAM) $(CFLAGS)  main.cpp $(LDFLAGS)

.PHONY: all clean

clean:
	rm -f $(PROGRAM) *.o
